### ISSUE TITLE
Update README to reflect 2018

### ISSUE THREAD

**Issue by Alexbay218** [Team612/612-2018#73]
Why does it still say 2017 steamworks?

**Comment by Ahmad-Bamba** [comment]
Don't forget to update or remove the link to Travis CI if applicable

**Comment by calvin-godfrey** [comment]
why did you close this now lmao

**Comment by Alexbay218** [comment]
was cleaning up my issues feed lol

**Comment by ZachPerkins1** [comment]
did we ever update the readme to say 2018

**Comment by calvin-godfrey** [comment]
Thank you for your valuable input, @ZachPerkins1

**Comment by toastertaster** [comment]
Wonderful surprise to see your banter today, thank you for the laughs. :smile: Hope you all are doing well.

**Comment by Ahmad-Bamba** [comment]
Github = best social media site, apparently

**Comment by ZachPerkins1** [comment]
Clearly repository hosting is just a facade to drive traffic to their social media endeavors

**Comment by Alexbay218** [comment]
ngl, I'm only on here to monitor a bug report I filed. everything I do is on gitlab now lol
